export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_PRODUCT_QUANTITY: "UPDATE_PRODUCT_QUANTITY",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",

  INCREMENT: "INCREMENT",
};
